apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
spec:
  replicas: 2
  template:
    metadata:
      name: javawebapppods
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: karthikkanish/java-web-app:tagVerion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: javawebapp
